spring:
  application:
    name: e-tilang

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka
  instance:
    preferIpAddress: true